# Generated by Django 3.2.9 on 2021-11-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('town_id', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.spot')),
                ('date', models.DateField()),
                ('wave_height', models.FloatField()),
                ('wave_period', models.FloatField()),
                ('wave_direction', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('temperature', models.FloatField()),
                ('sea_temperature', models.FloatField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Surfshop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('rating', models.FloatField()),
                ('operating_now', models.BooleanField()),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spot')),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.type'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reviewer')),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spot')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('url', models.TextField()),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spot')),
            ],
        ),
    ]
