# Generated by Django 3.2.9 on 2021-11-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='spot_id',
            new_name='spot',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='spot_id',
            new_name='spot',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='spot_id',
            new_name='spot',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='surfshop',
            old_name='spot_id',
            new_name='spot',
        ),
    ]
