# Generated by Django 3.2.9 on 2021-11-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('reviewer', models.OneToOneField(db_column='Reviewer_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.reviewer')),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'RECOMMEND',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='surfshop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
